stages:
  - deploy

deploy:
  stage: deploy
  variables:
    DEPLOY_NAME: "flix_webapp"
    DEPLOY_PATH: "docker/flix"
    ENV_FILE: ".env"
    REDIS_PASSWORD: "VETmbg3kPApUtw6f7ud5Ne"
    WEBDIS_HTTP_AUTH_USER: "flix"
    WEBDIS_HTTP_AUTH_PASSWORD: "x8EdUhQV3SDWkwMbTvaNsp"
    VITE_RADARR_BASE_URL: "http://62.210.136.137:7878"
    VITE_RADARR_API_KEY: "325d724593e2427a9c085df1e5905788"
    VITE_SONARR_BASE_URL: "http://62.210.136.137:8989"
    VITE_SONARR_API_KEY: "86df9c927b744a74a4a4dbed9c6e8768"
    VITE_IMDB_BASE_URL: "https://api.themoviedb.org/3"
    VITE_IMDB_API_KEY: "0d1dc24ae91481452ec415924333e3e9"
    VITE_CRYPT_KEY: "zmSKMpnF2cH5XZB3ufb6CA"
  script:
    - cp .env.dist $ENV_FILE
    - ssh-keyscan -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts
    - sshpass -p "$SSH_PASSWORD" scp -r -C -P "$SSH_PORT" ./ $SSH_USER@$SSH_HOST:$DEPLOY_PATH/$DEPLOY_NAME/
    - |
      sshpass -p "$SSH_PASSWORD" ssh -T -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" -p "$SSH_PORT" \
      "
      DEPLOY_NAME='$DEPLOY_NAME' \
      DEPLOY_PATH='$DEPLOY_PATH' \
      ENV_FILE='$ENV_FILE' \
      REDIS_PASSWORD='$REDIS_PASSWORD' \
      WEBDIS_HTTP_AUTH_USER='$WEBDIS_HTTP_AUTH_USER' \
      WEBDIS_HTTP_AUTH_PASSWORD='$WEBDIS_HTTP_AUTH_PASSWORD' \
      VITE_HTTP_PROTOCOL='$VITE_HTTP_PROTOCOL' \
      VITE_HOST_NAME='$VITE_HOST_NAME' \
      VITE_RADARR_BASE_URL='$VITE_RADARR_BASE_URL' \
      VITE_RADARR_API_KEY='$VITE_RADARR_API_KEY' \
      VITE_SONARR_BASE_URL='$VITE_SONARR_BASE_URL' \
      VITE_SONARR_API_KEY='$VITE_SONARR_API_KEY' \
      VITE_IMDB_BASE_URL='$VITE_IMDB_BASE_URL' \
      VITE_IMDB_API_KEY='$VITE_IMDB_API_KEY' \
      VITE_CRYPT_KEY='$VITE_CRYPT_KEY' \
      bash -s
      " << 'EOF'

      cd "$DEPLOY_PATH"/"$DEPLOY_NAME"

      sed -i "s|^REDIS_PASSWORD=.*|REDIS_PASSWORD=\"$REDIS_PASSWORD\"|" "$ENV_FILE"
      sed -i "s|^WEBDIS_HTTP_AUTH_USER=.*|WEBDIS_HTTP_AUTH_USER=\"$WEBDIS_HTTP_AUTH_USER\"|" "$ENV_FILE"
      sed -i "s|^WEBDIS_HTTP_AUTH_PASSWORD=.*|WEBDIS_HTTP_AUTH_PASSWORD=\"$WEBDIS_HTTP_AUTH_PASSWORD\"|" "$ENV_FILE"
      sed -i "s|^VITE_HTTP_PROTOCOL=.*|VITE_HTTP_PROTOCOL=\"$VITE_HTTP_PROTOCOL\"|" "$ENV_FILE"
      sed -i "s|^VITE_HOST_NAME=.*|VITE_HOST_NAME=\"$VITE_HOST_NAME\"|" "$ENV_FILE"
      sed -i "s|^VITE_RADARR_BASE_URL=.*|VITE_RADARR_BASE_URL=\"$VITE_RADARR_BASE_URL\"|" "$ENV_FILE"
      sed -i "s|^VITE_RADARR_API_KEY=.*|VITE_RADARR_API_KEY=\"$VITE_RADARR_API_KEY\"|" "$ENV_FILE"
      sed -i "s|^VITE_SONARR_BASE_URL=.*|VITE_SONARR_BASE_URL=\"$VITE_SONARR_BASE_URL\"|" "$ENV_FILE"
      sed -i "s|^VITE_SONARR_API_KEY=.*|VITE_SONARR_API_KEY=\"$VITE_SONARR_API_KEY\"|" "$ENV_FILE"
      sed -i "s|^VITE_IMDB_BASE_URL=.*|VITE_IMDB_BASE_URL=\"$VITE_IMDB_BASE_URL\"|" "$ENV_FILE"
      sed -i "s|^VITE_IMDB_API_KEY=.*|VITE_IMDB_API_KEY=\"$VITE_IMDB_API_KEY\"|" "$ENV_FILE"
      sed -i "s|^VITE_CRYPT_KEY=.*|VITE_CRYPT_KEY=\"$VITE_CRYPT_KEY\"|" "$ENV_FILE"

      ./restart.sh
      EOF
  only:
    - master
