services:
  app:
    image: ${APP_IMAGE}
    build:
      context: .
      dockerfile: ${APP_DOCKERFILE}
    restart: unless-stopped
    ports:
      - ${APP_PORT}:5173
    environment:
      NODE_ENV: ${NODE_ENV}

